ALTER TABLE FreeholdHistory
    MODIFY COLUMN eventType ENUM (
        'BUY', 'AUCTION_BUY', 'OFFER_BUY',
        'SET_PRICE', 'UNSET_PRICE', 'SET_TITLEHOLDER', 'UNSET_TITLEHOLDER'
    ) NOT NULL;

ALTER TABLE LeaseholdHistory
    MODIFY COLUMN eventType ENUM (
        'RENT', 'UNRENT', 'RENEW', 'LEASEHOLD_EXPIRY',
        'SET_DURATION', 'SET_LANDLORD', 'SET_TENANT', 'UNSET_TENANT', 'SET_MAX_EXTENSIONS'
    ) NOT NULL;
